### ISSUE TITLE
traceback with zero length keys

### ISSUE THREAD

**Issue by oberstet** [crossbario/zlmdb#2]
It should be possible to watch for all keys using

* `keys = [KeySet(b'm', prefix=True)}`

when providing a filter for `etcd.watch(keys, on_change)`.

However, this triggers a bug:

```console
Traceback (most recent call last):
  File "/home/oberstet/cpy370_5/lib/python3.7/site-packages/twisted/internet/defer.py", line 460, in callback
    self._startRunCallbacks(result)
  File "/home/oberstet/cpy370_5/lib/python3.7/site-packages/twisted/internet/defer.py", line 568, in _startRunCallbacks
    self._runCallbacks()
  File "/home/oberstet/cpy370_5/lib/python3.7/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/home/oberstet/cpy370_5/lib/python3.7/site-packages/twisted/internet/defer.py", line 1475, in gotResult
    _inlineCallbacks(r, g, status)
--- <exception caught here> ---
  File "/home/oberstet/cpy370_5/lib/python3.7/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "tests/test_etcd.py", line 18, in main
    d = etcd.watch(keys, on_change)
  File "/home/oberstet/scm/crossbario/txaio-etcd/txaioetcd/_client_tx.py", line 409, in watch
    d = self._start_watching(keys, on_watch, filters, start_revision, return_previous)
  File "/home/oberstet/scm/crossbario/txaio-etcd/txaioetcd/_client_tx.py", line 440, in _start_watching
    range_end = _increment_last_byte(key.key)
  File "/home/oberstet/scm/crossbario/txaio-etcd/txaioetcd/_types.py", line 47, in _increment_last_byte
    s[-1] = s[-1] + 1
builtins.IndexError: bytearray index out of range
```

**Comment by oberstet** [comment]
closed: misplace here as txaio-etcd related ..
