### ISSUE TITLE
deleting from table with nullable index

### ISSUE THREAD

**Issue by oberstet** [crossbario/zlmdb#6]
In **cfc-functests**:

* test_organizations_crud
* test_webcluster_crud

```
2019-04-20T18:16:13+0200 2019-04-20T18:16:13+0200 [Container   28502] UserManager.create_organization(organization={}, details=CallDetails(registration=<autobahn.wamp.request.Registration object at 0x7f05f0631b38>, progress=None, caller=3159352971539072, caller_authid=superuser, caller_authrole=user, procedure=<crossbarfabriccenter.user.create_organization>, enc_algo=None, forward_for=None))
2019-04-20T18:16:13+0200 2019-04-20T18:16:13+0200 [Container   28502] new Organization object stored in database:
2019-04-20T18:16:13+0200 
2019-04-20T18:16:13+0200 {'name': None,
2019-04-20T18:16:13+0200  'oid': '73c0a037-3c43-4ff2-a9f5-26b2a16a254f',
2019-04-20T18:16:13+0200  'otype': None,
2019-04-20T18:16:13+0200  'registered': None}
2019-04-20T18:16:13+0200 
2019-04-20T18:16:13+0200 Event received on "cfc.user.on_organization_created" {'oid': '73c0a037-3c43-4ff2-a9f5-26b2a16a254f', 'name': None, 'otype': None, 'registered': None} EventDetails(subscription=Subscription(id=5731476024697015, is_active=True), publication=2344536254292897, publisher=None, publisher_authid=None, publisher_authrole=None, topic=<crossbarfabriccenter.user.on_organization_created>, retained=None, enc_algo=None, forward_for=None)
2019-04-20T18:16:13+0200 {'oid': '73c0a037-3c43-4ff2-a9f5-26b2a16a254f', 'name': None, 'otype': None, 'registered': None}
2019-04-20T18:16:13+0200 2019-04-20T18:16:13+0200 [Container   28502] Management API event <on_organization_created> published:
2019-04-20T18:16:13+0200 {'oid': '73c0a037-3c43-4ff2-a9f5-26b2a16a254f', 'name': None, 'otype': None, 'registered': None}

2019-04-20T18:16:13+0200 2019-04-20T18:16:13+0200 [Container   28502] UserManager.list_organizations(details=CallDetails(registration=<autobahn.wamp.request.Registration object at 0x7f05f0631c78>, progress=None, caller=3159352971539072, caller_authid=superuser, caller_authrole=user, procedure=<crossbarfabriccenter.user.list_organizations>, enc_algo=None, forward_for=None))
2019-04-20T18:16:13+0200 ['30928e6b-41d9-451a-840f-55edbc2aab60', '73c0a037-3c43-4ff2-a9f5-26b2a16a254f', '892f07f7-09d7-4ec9-8cec-731d6ad76206']
2019-04-20T18:16:13+0200 2019-04-20T18:16:13+0200 [Container   28502] UserManager.delete_organization(details=CallDetails(registration=<autobahn.wamp.request.Registration object at 0x7f05f0631ae8>, progress=None, caller=3159352971539072, caller_authid=superuser, caller_authrole=user, procedure=<crossbarfabriccenter.user.delete_organization>, enc_algo=None, forward_for=None))
2019-04-20T18:16:13+0200 2019-04-20T18:16:13+0200 [Container   28502] DomainController.onUserError(): "AssertionError: "
2019-04-20T18:16:13+0200 Traceback (most recent call last):
2019-04-20T18:16:13+0200   File "/home/oberstet/cpy373_1/lib/python3.7/site-packages/autobahn/wamp/protocol.py", line 1006, in onMessage
2019-04-20T18:16:13+0200     on_reply = txaio.as_future(endpoint.fn, *invoke_args, **invoke_kwargs)
2019-04-20T18:16:13+0200   File "/home/oberstet/cpy373_1/lib/python3.7/site-packages/txaio/tx.py", line 428, in as_future
2019-04-20T18:16:13+0200     return ensureDeferred(fun(*args, **kwargs))
2019-04-20T18:16:13+0200   File "/home/oberstet/cpy373_1/lib/python3.7/site-packages/twisted/internet/defer.py", line 911, in ensureDeferred
2019-04-20T18:16:13+0200     return _cancellableInlineCallbacks(coro)
2019-04-20T18:16:13+0200   File "/home/oberstet/cpy373_1/lib/python3.7/site-packages/twisted/internet/defer.py", line 1529, in _cancellableInlineCallbacks
2019-04-20T18:16:13+0200     _inlineCallbacks(None, g, status)
2019-04-20T18:16:13+0200 --- <exception caught here> ---
2019-04-20T18:16:13+0200   File "/home/oberstet/cpy373_1/lib/python3.7/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
2019-04-20T18:16:13+0200     result = g.send(result)
2019-04-20T18:16:13+0200   File "/home/oberstet/scm/crossbario/crossbarfx/crossbarfx/master/node/user.py", line 198, in delete_organization
2019-04-20T18:16:13+0200     del self.schema.organizations[txn, oid]
2019-04-20T18:16:13+0200   File "/home/oberstet/cpy373_1/lib/python3.7/site-packages/zlmdb/_pmap.py", line 463, in __delitem__
2019-04-20T18:16:13+0200     _idx_key = struct.pack('>H', index.pmap._slot) + index.pmap._serialize_key(index.fkey(value))
2019-04-20T18:16:13+0200   File "/home/oberstet/cpy373_1/lib/python3.7/site-packages/zlmdb/_types.py", line 272, in _serialize_key
2019-04-20T18:16:13+0200     assert type(key) == six.text_type
2019-04-20T18:16:13+0200 builtins.AssertionError: 
2019-04-20T18:16:13+0200 
```

or

```
2019-04-20T18:16:20+0200 2019-04-20T18:16:20+0200 [Container   28563] WebClusterManager.create_webcluster(webcluster={'tcp_port': 8080, 'tcp_shared': True, 'tcp_interface': '127.0.0.1', 'tcp_backlog': 100, 'http_display_tracebacks': True}, details=CallDetails(registration=<autobahn.wamp.request.Registration object at 0x7fb7e55ff5e8>, progress=None, caller=6236535363633262, caller_authid=superuser, caller_authrole=owner, procedure=<crossbarfabriccenter.mrealm.webcluster.create_webcluster>, enc_algo=None, forward_for=None))
2019-04-20T18:16:20+0200 2019-04-20T18:16:20+0200 [Container   28563] new WebCluster object stored in database:
2019-04-20T18:16:20+0200 
2019-04-20T18:16:20+0200 {'changed': None,
2019-04-20T18:16:20+0200  'http_access_log': None,
2019-04-20T18:16:20+0200  'http_client_timeout': None,
2019-04-20T18:16:20+0200  'http_display_tracebacks': True,
2019-04-20T18:16:20+0200  'http_hsts': None,
2019-04-20T18:16:20+0200  'http_hsts_max_age': None,
2019-04-20T18:16:20+0200  'name': None,
2019-04-20T18:16:20+0200  'oid': '8ae38960-f291-403a-a1dd-2f6b53dfc2c9',
2019-04-20T18:16:20+0200  'status': 'STOPPED',
2019-04-20T18:16:20+0200  'tcp_backlog': 100,
2019-04-20T18:16:20+0200  'tcp_interface': '127.0.0.1',
2019-04-20T18:16:20+0200  'tcp_port': 8080,
2019-04-20T18:16:20+0200  'tcp_shared': True,
2019-04-20T18:16:20+0200  'tcp_version': None,
2019-04-20T18:16:20+0200  'tls_ca_certificates': None,
2019-04-20T18:16:20+0200  'tls_certificate': None,
2019-04-20T18:16:20+0200  'tls_chain_certificates': None,
2019-04-20T18:16:20+0200  'tls_ciphers': None,
2019-04-20T18:16:20+0200  'tls_dhparam': None,
2019-04-20T18:16:20+0200  'tls_key': None}
2019-04-20T18:16:20+0200 
2019-04-20T18:16:20+0200 2019-04-20T18:16:20+0200 [Container   28563] Management API event <on_webcluster_created> published:
2019-04-20T18:16:20+0200 {'oid': '8ae38960-f291-403a-a1dd-2f6b53dfc2c9', 'name': None, 'status': 'STOPPED', 'changed': None, 'tcp_version': None, 'tcp_port': 8080, 'tcp_shared': True, 'tcp_interface': '127.0.0.1', 'tcp_backlog': 100, 'tls_key': None, 'tls_certificate': None, 'tls_chain_certificates': None, 'tls_ca_certificates': None, 'tls_dhparam': None, 'tls_ciphers': None, 'http_client_timeout': None, 'http_hsts': None, 'http_hsts_max_age': None, 'http_access_log': None, 'http_display_tracebacks': True}
2019-04-20T18:16:20+0200 {'oid': '8ae38960-f291-403a-a1dd-2f6b53dfc2c9', 'name': None, 'status': 'STOPPED', 'changed': None, 'tcp_version': None, 'tcp_port': 8080, 'tcp_shared': True, 'tcp_interface': '127.0.0.1', 'tcp_backlog': 100, 'tls_key': None, 'tls_certificate': None, 'tls_chain_certificates': None, 'tls_ca_certificates': None, 'tls_dhparam': None, 'tls_ciphers': None, 'http_client_timeout': None, 'http_hsts': None, 'http_hsts_max_age': None, 'http_access_log': None, 'http_display_tracebacks': True}
2019-04-20T18:16:20+0200 2019-04-20T18:16:20+0200 [Container   28563] WebClusterManager.list_webclusters(details=CallDetails(registration=<autobahn.wamp.request.Registration object at 0x7fb7e55ff8b8>, progress=None, caller=6236535363633262, caller_authid=superuser, caller_authrole=owner, procedure=<crossbarfabriccenter.mrealm.webcluster.list_webclusters>, enc_algo=None, forward_for=None))
2019-04-20T18:16:20+0200 ['20087354-66ae-4c99-ab63-469c30aa1e7f', '8ae38960-f291-403a-a1dd-2f6b53dfc2c9']
2019-04-20T18:16:20+0200 2019-04-20T18:16:20+0200 [Container   28563] WebClusterManager.add_webcluster_service(webcluster_oid=8ae38960-f291-403a-a1dd-2f6b53dfc2c9, path=info, webservice={'type': 'nodeinfo'}, details=CallDetails(registration=<autobahn.wamp.request.Registration object at 0x7fb7e55ff598>, progress=None, caller=6236535363633262, caller_authid=superuser, caller_authrole=owner, procedure=<crossbarfabriccenter.mrealm.webcluster.add_webcluster_service>, enc_algo=None, forward_for=None))
2019-04-20T18:16:20+0200 2019-04-20T18:16:20+0200 [Container   28563] New WebService object stored in database:
2019-04-20T18:16:20+0200 
2019-04-20T18:16:20+0200 {'oid': 'd424fa2a-2afb-4cba-b03e-8f8f56f6ac40',
2019-04-20T18:16:20+0200  'path': 'info',
2019-04-20T18:16:20+0200  'type': 'nodeinfo',
2019-04-20T18:16:20+0200  'webcluster_oid': '8ae38960-f291-403a-a1dd-2f6b53dfc2c9'}
2019-04-20T18:16:20+0200 
2019-04-20T18:16:20+0200 2019-04-20T18:16:20+0200 [Container   28563] Management API event <on_webservice_added> published:
2019-04-20T18:16:20+0200 {'oid': 'd424fa2a-2afb-4cba-b03e-8f8f56f6ac40', 'webcluster_oid': '8ae38960-f291-403a-a1dd-2f6b53dfc2c9', 'path': 'info', 'type': 'nodeinfo'}
2019-04-20T18:16:20+0200 {'oid': 'd424fa2a-2afb-4cba-b03e-8f8f56f6ac40', 'webcluster_oid': '8ae38960-f291-403a-a1dd-2f6b53dfc2c9', 'path': 'info', 'type': 'nodeinfo'}
2019-04-20T18:16:20+0200 2019-04-20T18:16:20+0200 [Container   28563] WebClusterManager.add_webcluster_service(webcluster_oid=8ae38960-f291-403a-a1dd-2f6b53dfc2c9, path=temp, webservice={'type': 'static', 'directory': '/tmp', 'options': {'enable_directory_listing': True}}, details=CallDetails(registration=<autobahn.wamp.request.Registration object at 0x7fb7e55ff598>, progress=None, caller=6236535363633262, caller_authid=superuser, caller_authrole=owner, procedure=<crossbarfabriccenter.mrealm.webcluster.add_webcluster_service>, enc_algo=None, forward_for=None))
2019-04-20T18:16:20+0200 2019-04-20T18:16:20+0200 [Container   28563] New WebService object stored in database:
2019-04-20T18:16:20+0200 
2019-04-20T18:16:20+0200 {'directory': '/tmp',
2019-04-20T18:16:20+0200  'oid': '925e08db-8906-4956-8a78-5b996a55fc52',
2019-04-20T18:16:20+0200  'options': {'enable_directory_listing': True},
2019-04-20T18:16:20+0200  'path': 'temp',
2019-04-20T18:16:20+0200  'type': 'static',
2019-04-20T18:16:20+0200  'webcluster_oid': '8ae38960-f291-403a-a1dd-2f6b53dfc2c9'}
2019-04-20T18:16:20+0200 
2019-04-20T18:16:20+0200 2019-04-20T18:16:20+0200 [Container   28563] Management API event <on_webservice_added> published:
2019-04-20T18:16:20+0200 {'oid': '925e08db-8906-4956-8a78-5b996a55fc52', 'directory': '/tmp', 'options': {'enable_directory_listing': True}, 'webcluster_oid': '8ae38960-f291-403a-a1dd-2f6b53dfc2c9', 'path': 'temp', 'type': 'static'}
2019-04-20T18:16:20+0200 {'oid': '925e08db-8906-4956-8a78-5b996a55fc52', 'directory': '/tmp', 'options': {'enable_directory_listing': True}, 'webcluster_oid': '8ae38960-f291-403a-a1dd-2f6b53dfc2c9', 'path': 'temp', 'type': 'static'}
2019-04-20T18:16:20+0200 2019-04-20T18:16:20+0200 [Container   28563] WebClusterManager.delete_webcluster(details=CallDetails(registration=<autobahn.wamp.request.Registration object at 0x7fb7e55ff638>, progress=None, caller=6236535363633262, caller_authid=superuser, caller_authrole=owner, procedure=<crossbarfabriccenter.mrealm.webcluster.delete_webcluster>, enc_algo=None, forward_for=None))
2019-04-20T18:16:20+0200 2019-04-20T18:16:20+0200 [Container   28563] MrealmController.onUserError(): "AssertionError: "
2019-04-20T18:16:20+0200 Traceback (most recent call last):
2019-04-20T18:16:20+0200   File "/home/oberstet/cpy373_1/lib/python3.7/site-packages/autobahn/wamp/protocol.py", line 1006, in onMessage
2019-04-20T18:16:20+0200     on_reply = txaio.as_future(endpoint.fn, *invoke_args, **invoke_kwargs)
2019-04-20T18:16:20+0200   File "/home/oberstet/cpy373_1/lib/python3.7/site-packages/txaio/tx.py", line 428, in as_future
2019-04-20T18:16:20+0200     return ensureDeferred(fun(*args, **kwargs))
2019-04-20T18:16:20+0200   File "/home/oberstet/cpy373_1/lib/python3.7/site-packages/twisted/internet/defer.py", line 911, in ensureDeferred
2019-04-20T18:16:20+0200     return _cancellableInlineCallbacks(coro)
2019-04-20T18:16:20+0200   File "/home/oberstet/cpy373_1/lib/python3.7/site-packages/twisted/internet/defer.py", line 1529, in _cancellableInlineCallbacks
2019-04-20T18:16:20+0200     _inlineCallbacks(None, g, status)
2019-04-20T18:16:20+0200 --- <exception caught here> ---
2019-04-20T18:16:20+0200   File "/home/oberstet/cpy373_1/lib/python3.7/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
2019-04-20T18:16:20+0200     result = g.send(result)
2019-04-20T18:16:20+0200   File "/home/oberstet/scm/crossbario/crossbarfx/crossbarfx/master/mrealm/webcluster.py", line 255, in delete_webcluster
2019-04-20T18:16:20+0200     del self.schema.webclusters[txn, oid]
2019-04-20T18:16:20+0200   File "/home/oberstet/cpy373_1/lib/python3.7/site-packages/zlmdb/_pmap.py", line 463, in __delitem__
2019-04-20T18:16:20+0200     _idx_key = struct.pack('>H', index.pmap._slot) + index.pmap._serialize_key(index.fkey(value))
2019-04-20T18:16:20+0200   File "/home/oberstet/cpy373_1/lib/python3.7/site-packages/zlmdb/_types.py", line 272, in _serialize_key
2019-04-20T18:16:20+0200     assert type(key) == six.text_type
2019-04-20T18:16:20+0200 builtins.AssertionError: 
2019-04-20T18:16:20+0200 
```

**Comment by oberstet** [comment]
this is fixed on master, and we have CI tests here https://github.com/crossbario/zlmdb/blob/master/zlmdb/tests/test_pmap_indexes.py
